# Generated by Django 4.1.3 on 2022-12-02 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='movie',
            unique_together={('name', 'unicode_name', 'year')},
        ),
    ]
