# Generated by Django 4.1.3 on 2022-12-06 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='city_of_birth',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='actor',
            name='unicode_name',
            field=models.CharField(help_text='Unaccented lowercase string for searching', max_length=255),
        ),
        migrations.AlterField(
            model_name='movie',
            name='unicode_name',
            field=models.CharField(help_text='Unaccented lowercase string for searching', max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='actor',
            unique_together={('name', 'unicode_name', 'date_of_birth', 'city_of_birth')},
        ),
    ]
